name: task day1
on: push


jobs:
    docker:
        runs-on: ubuntu-latest
        env:  
            IMAGE_NAME: my-docker-image
        steps:
            - name: Set up Docker
              uses: docker/setup-docker-action@v4

            - name: checkout
              uses: actions/checkout@v4  

            - name: Login to Azure Container Registry
              run: |
                    echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
                    "${{ vars.DOCKER_REGISTRY }}" \
                    -u "${{ vars.DOCKER_USERNAME }}" \
                    --password-stdin

            - name: Build Docker Image
              run: |
                docker build -t ${{ vars.DOCKER_REGISTRY }}/$IMAGE_NAME:latest .

            - name: Push Docker Image
              run: |
                docker push ${{ vars.DOCKER_REGISTRY }}/$IMAGE_NAME:latest